#! /bin/sh

bspc config border_width        3
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#EC6360"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Pencil desktop=^4 follow=on 
bspc rule -a Gimp desktop=^5 follow=on 
bspc rule -a inkscape desktop=^6 follow=on
bspc rule -a Thunderbird desktop=^3 follow=on
bspc rule -a vlc floating=on
bspc rule -a xfce4-appfinder floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Chromium follow=on
