#! /bin/sh

sxhkd &

bspc config border_width        1
bspc config window_gap          30
bspc config bottom_padding      -5

bspc config split_ratio         0.5

bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config click_to_focus      true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config normal_border_color         "#000000"
bspc config focused_border_color        "#CB4B16"
bspc config presel_feedback_color         "#DC322F"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Inkscape desktop='^4' follow=on
bspc rule -a Thunderbird desktop='^6' follow=on
bspc rule -a Gimp desktop='^5' follow=on
bspc rule -a vlc state=floating
bspc rule -a URxvt state=floating

urxvt -e ncmpcpp &

polybar primary &
